import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
} from "docx";
import type { GameConcept, SimulationResults } from "./simulation";

const COLORS = {
  primary: "#2D5F4F",
  accent: "#5B9F8B",
  dark: "#1A1F1E",
  light: "#F8FAF9",
  textMuted: "#6B7280",
};

const FONT = "helvetica";

export interface ExportOptions {
  format: "pdf" | "docx";
  filename: string;
  sections: {
    gameSummary: boolean;
    performanceScore: boolean;
    population: boolean;
    archetypeFit: boolean;
    sessionJourney: boolean;
    recommendation: boolean;
    featureInteraction: boolean;
    stopReasons: boolean;
    dataInterpretation: boolean;
    similarGames: boolean;
    gambleImpact: boolean;
    symbolSwapImpact: boolean;
  };
}

async function captureChartAsImage(elementId: string): Promise<string | null> {
  try {
    const element = document.getElementById(elementId);
    if (!element) return null;
    const canvas = await html2canvas(element, {
      backgroundColor: "#ffffff",
      scale: 2,
      logging: false,
    });
    return canvas.toDataURL("image/png");
  } catch (err) {
    console.warn("Failed to capture chart:", err);
    return null;
  }
}

export async function exportToPDF(
  game: GameConcept,
  results: SimulationResults,
  options: ExportOptions,
): Promise<void> {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPos = margin;

  const addFooter = (pageNum: number) => {
    doc.setFontSize(8);
    doc.setTextColor(COLORS.textMuted);
    doc.text(
      `Generated by LaunchIndex • ${new Date().toLocaleDateString()}`,
      margin,
      pageHeight - 10,
    );
    doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  };

  const checkNewPage = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - 25) {
      addFooter(doc.getNumberOfPages());
      doc.addPage();
      yPos = margin;
      return true;
    }
    return false;
  };

  // Cover
  doc.setFillColor(COLORS.primary);
  doc.rect(0, 0, pageWidth, 80, "F");
  doc.setTextColor("#FFFFFF");
  doc.setFontSize(28);
  doc.setFont(FONT, "bold");
  doc.text(game.gameName || "Untitled Game", pageWidth / 2, 40, { align: "center" });
  doc.setFontSize(13);
  doc.setFont(FONT, "normal");
  doc.text("Game Concept Simulation Report", pageWidth / 2, 55, { align: "center" });
  doc.setFontSize(10);
  doc.setTextColor(COLORS.light);
  doc.text("LaunchIndex", pageWidth - margin, 15, { align: "right" });

  doc.setTextColor(COLORS.dark);
  doc.setFontSize(11);
  doc.setFont(FONT, "normal");
  yPos = 100;
  doc.text(
    `Report Date: ${new Date().toLocaleDateString("en-GB", {
      day: "numeric",
      month: "long",
      year: "numeric",
    })}`,
    margin,
    yPos,
  );

  addFooter(1);
  doc.addPage();
  yPos = margin;

  // Executive Summary
  if (options.sections.performanceScore) {
    doc.setFontSize(20);
    doc.setFont(FONT, "bold");
    doc.setTextColor(COLORS.primary);
    doc.text("Executive Summary", margin, yPos);
    yPos += 14;

    doc.setFontSize(48);
    doc.setTextColor(COLORS.primary);
    doc.text(results.performanceScore.overall.toFixed(1), margin, yPos);
    doc.setFontSize(12);
    doc.setTextColor(COLORS.textMuted);
    doc.text("/10", margin + 28, yPos);
    doc.setTextColor(COLORS.dark);
    doc.text("Overall Performance", margin + 40, yPos);
    yPos += 14;

    const metrics = [
      { label: "Session Quality", value: results.performanceScore.sessionQuality },
      { label: "Player Retention", value: results.performanceScore.playerRetention },
      { label: "Feature Efficiency", value: results.performanceScore.featureEfficiency },
      { label: "Market Fit", value: results.performanceScore.marketFit },
    ];

    const boxWidth = (contentWidth - 10) / 2;
    const boxHeight = 25;
    metrics.forEach((m, idx) => {
      const col = idx % 2;
      const row = Math.floor(idx / 2);
      const xOffset = margin + col * (boxWidth + 10);
      const boxY = yPos + row * (boxHeight + 5);
      doc.setFillColor(COLORS.light);
      doc.roundedRect(xOffset, boxY, boxWidth, boxHeight, 3, 3, "F");
      doc.setFontSize(20);
      doc.setFont(FONT, "bold");
      doc.setTextColor(COLORS.primary);
      doc.text(m.value.toFixed(1), xOffset + 5, boxY + 13);
      doc.setFontSize(10);
      doc.setFont(FONT, "normal");
      doc.setTextColor(COLORS.dark);
      doc.text(m.label, xOffset + 5, boxY + 21);
    });
    yPos += Math.ceil(metrics.length / 2) * (boxHeight + 5) + 10;
  }

  if (options.sections.recommendation) {
    checkNewPage(45);
    doc.setFillColor(COLORS.accent);
    doc.roundedRect(margin, yPos, contentWidth, 35, 3, 3, "F");
    doc.setFontSize(12);
    doc.setFont(FONT, "bold");
    doc.setTextColor("#FFFFFF");
    doc.text("Recommendation", margin + 5, yPos + 9);
    doc.setFontSize(11);
    doc.setFont(FONT, "normal");
    const recLines = doc.splitTextToSize(results.recommendation, contentWidth - 10);
    doc.text(recLines, margin + 5, yPos + 18);
    yPos += 45;
  }

  // Game Overview
  if (options.sections.gameSummary) {
    checkNewPage(60);
    doc.setFontSize(16);
    doc.setFont(FONT, "bold");
    doc.setTextColor(COLORS.primary);
    doc.text("Game Overview", margin, yPos);
    yPos += 8;

    const overviewData: [string, string][] = [
      ["Game Type", game.gameType],
      ["Grid Layout", game.gridLayout],
      ["Volatility", game.volatility],
      ["RTP Target", `${game.rtpTarget}%`],
      ["Top Win", `${game.topWin}×`],
      ["Target Markets", (game.targetMarkets || []).join(", ") || "—"],
    ];

    autoTable(doc, {
      startY: yPos,
      body: overviewData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 10, cellPadding: 3 },
      columnStyles: {
        0: { fontStyle: "bold", textColor: [26, 31, 30], cellWidth: 50 },
        1: { textColor: [107, 114, 128] },
      },
      theme: "plain",
    });
    yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
  }

  // Player Metrics
  if (options.sections.population) {
    checkNewPage(80);
    doc.setFontSize(16);
    doc.setFont(FONT, "bold");
    doc.setTextColor(COLORS.primary);
    doc.text("Player Metrics", margin, yPos);
    yPos += 8;

    const halfW = contentWidth / 2 - 5;
    doc.setFillColor(COLORS.light);
    doc.roundedRect(margin, yPos, halfW, 30, 3, 3, "F");
    doc.roundedRect(margin + halfW + 10, yPos, halfW, 30, 3, 3, "F");
    doc.setFontSize(22);
    doc.setFont(FONT, "bold");
    doc.setTextColor(COLORS.primary);
    doc.text(`${results.simulatedPopulation.retentionD1}%`, margin + 8, yPos + 16);
    doc.text(`${results.simulatedPopulation.retentionD7}%`, margin + halfW + 18, yPos + 16);
    doc.setFontSize(10);
    doc.setFont(FONT, "normal");
    doc.setTextColor(COLORS.textMuted);
    doc.text("Day 1 Retention", margin + 8, yPos + 24);
    doc.text("Day 7 Retention", margin + halfW + 18, yPos + 24);
    yPos += 38;

    const popData: [string, string][] = [
      ["Churn Rate", `${results.simulatedPopulation.churnRate}%`],
      ["Avg Session Duration", `${results.simulatedPopulation.avgSessionDurationMinutes} min`],
      ["Avg Rounds per Session", `${results.simulatedPopulation.avgRoundsPerSession}`],
    ];
    autoTable(doc, {
      startY: yPos,
      body: popData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 10, cellPadding: 3 },
      columnStyles: { 0: { fontStyle: "bold", cellWidth: 60 } },
      theme: "plain",
    });
    yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
  }

  // Archetype Fit
  if (options.sections.archetypeFit && results.archetypeFitScores?.length) {
    checkNewPage(60);
    doc.setFontSize(16);
    doc.setFont(FONT, "bold");
    doc.setTextColor(COLORS.primary);
    doc.text("Archetype Fit Analysis", margin, yPos);
    yPos += 8;

    const fitData = results.archetypeFitScores.map((a) => [
      a.archetype,
      a.finalScore.toFixed(1),
      a.fitLabel,
    ]);

    autoTable(doc, {
      startY: yPos,
      head: [["Archetype", "Score", "Fit"]],
      body: fitData,
      margin: { left: margin, right: margin },
      styles: { fontSize: 10, cellPadding: 4 },
      headStyles: { fillColor: [45, 95, 79], textColor: 255, fontStyle: "bold" },
      columnStyles: {
        1: { halign: "center", fontStyle: "bold" },
        2: { halign: "center" },
      },
      theme: "grid",
    });
    yPos = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 12;
  }

  // Session Journey chart
  if (options.sections.sessionJourney) {
    checkNewPage(100);
    doc.setFontSize(16);
    doc.setFont(FONT, "bold");
    doc.setTextColor(COLORS.primary);
    doc.text("Session Journey", margin, yPos);
    yPos += 8;

    const chartImage = await captureChartAsImage("session-journey-chart");
    if (chartImage) {
      const imgHeight = 80;
      doc.addImage(chartImage, "PNG", margin, yPos, contentWidth, imgHeight);
      yPos += imgHeight + 10;
    } else {
      doc.setFontSize(10);
      doc.setTextColor(COLORS.textMuted);
      doc.setFont(FONT, "normal");
      doc.text("(Chart could not be captured)", margin, yPos);
      yPos += 10;
    }
  }

  // Data Interpretation
  if (options.sections.dataInterpretation && results.dataInterpretation?.length) {
    checkNewPage(60);
    doc.setFontSize(16);
    doc.setFont(FONT, "bold");
    doc.setTextColor(COLORS.primary);
    doc.text("Key Insights", margin, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont(FONT, "normal");
    doc.setTextColor(COLORS.dark);

    results.dataInterpretation.forEach((insight, idx) => {
      const heading = `${idx + 1}. ${insight.category}`;
      const lines = doc.splitTextToSize(insight.narrative || "", contentWidth - 6);
      checkNewPage(8 + lines.length * 5 + 4);
      doc.setFont(FONT, "bold");
      doc.text(heading, margin, yPos);
      yPos += 5;
      doc.setFont(FONT, "normal");
      doc.text(lines, margin + 4, yPos);
      yPos += lines.length * 5 + 4;
    });
    yPos += 5;
  }

  addFooter(doc.getNumberOfPages());
  doc.save(`${options.filename}.pdf`);
}

// ============================================
// DOCX EXPORT
// ============================================

const cellBorder = { style: BorderStyle.SINGLE, size: 4, color: "CCCCCC" };
const cellBorders = {
  top: cellBorder,
  bottom: cellBorder,
  left: cellBorder,
  right: cellBorder,
};

function labelCell(label: string, value: string): TableRow {
  return new TableRow({
    children: [
      new TableCell({
        borders: cellBorders,
        width: { size: 35, type: WidthType.PERCENTAGE },
        children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })],
      }),
      new TableCell({
        borders: cellBorders,
        width: { size: 65, type: WidthType.PERCENTAGE },
        children: [new Paragraph({ children: [new TextRun(value)] })],
      }),
    ],
  });
}

export async function exportToDOCX(
  game: GameConcept,
  results: SimulationResults,
  options: ExportOptions,
): Promise<void> {
  const children: (Paragraph | Table)[] = [];

  children.push(
    new Paragraph({
      text: game.gameName || "Untitled Game",
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    }),
    new Paragraph({
      text: "Game Concept Simulation Report",
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      text: `Report Date: ${new Date().toLocaleDateString("en-GB", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })}`,
      spacing: { after: 400 },
    }),
  );

  if (options.sections.performanceScore) {
    children.push(
      new Paragraph({
        text: "Executive Summary",
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Overall Performance Score: ", bold: true }),
          new TextRun({
            text: `${results.performanceScore.overall.toFixed(1)} / 10`,
            size: 28,
          }),
        ],
        spacing: { after: 120 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Session Quality: ", bold: true }),
          new TextRun(`${results.performanceScore.sessionQuality.toFixed(1)}`),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Player Retention: ", bold: true }),
          new TextRun(`${results.performanceScore.playerRetention.toFixed(1)}`),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Feature Efficiency: ", bold: true }),
          new TextRun(`${results.performanceScore.featureEfficiency.toFixed(1)}`),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Market Fit: ", bold: true }),
          new TextRun(`${results.performanceScore.marketFit.toFixed(1)}`),
        ],
        spacing: { after: 200 },
      }),
    );
  }

  if (options.sections.recommendation) {
    children.push(
      new Paragraph({
        text: "Recommendation",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 120 },
      }),
      new Paragraph({
        children: [new TextRun(results.recommendation)],
        spacing: { after: 300 },
      }),
    );
  }

  if (options.sections.gameSummary) {
    children.push(
      new Paragraph({
        text: "Game Overview",
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          labelCell("Game Type", game.gameType),
          labelCell("Grid Layout", game.gridLayout),
          labelCell("Volatility", game.volatility),
          labelCell("RTP Target", `${game.rtpTarget}%`),
          labelCell("Top Win", `${game.topWin}×`),
          labelCell("Target Markets", (game.targetMarkets || []).join(", ") || "—"),
        ],
      }),
      new Paragraph({ text: "", spacing: { after: 200 } }),
    );
  }

  if (options.sections.population) {
    children.push(
      new Paragraph({
        text: "Player Metrics",
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          labelCell("Day 1 Retention", `${results.simulatedPopulation.retentionD1}%`),
          labelCell("Day 7 Retention", `${results.simulatedPopulation.retentionD7}%`),
          labelCell("Churn Rate", `${results.simulatedPopulation.churnRate}%`),
          labelCell(
            "Avg Session Duration",
            `${results.simulatedPopulation.avgSessionDurationMinutes} min`,
          ),
          labelCell(
            "Avg Rounds per Session",
            `${results.simulatedPopulation.avgRoundsPerSession}`,
          ),
        ],
      }),
      new Paragraph({ text: "", spacing: { after: 200 } }),
    );
  }

  if (options.sections.archetypeFit && results.archetypeFitScores?.length) {
    children.push(
      new Paragraph({
        text: "Archetype Fit Analysis",
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }),
    );
    results.archetypeFitScores.forEach((a) => {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${a.archetype}: `, bold: true }),
            new TextRun(`${a.finalScore.toFixed(1)} — ${a.fitLabel}`),
          ],
        }),
      );
    });
    children.push(new Paragraph({ text: "", spacing: { after: 200 } }));
  }

  if (options.sections.dataInterpretation && results.dataInterpretation?.length) {
    children.push(
      new Paragraph({
        text: "Key Insights",
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }),
    );
    results.dataInterpretation.forEach((insight, idx) => {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${idx + 1}. ${insight.category}`, bold: true }),
          ],
          spacing: { before: 120, after: 60 },
        }),
        new Paragraph({
          children: [new TextRun(insight.narrative || "")],
          spacing: { after: 80 },
        }),
      );
    });
  }

  children.push(
    new Paragraph({
      text: `Generated by LaunchIndex • ${new Date().toLocaleDateString()}`,
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    }),
  );

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${options.filename}.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
