// ============================================================
// LaunchIndex — Retrospective Validation Dataset
// 20 released titles with verified game math inputs and
// known market outcomes. Used to measure prediction accuracy
// of the simulation engine against real-world performance.
//
// Sources: provider game pages, certified RTP documents,
// Slotcatalog, BGAOC, industry publications.
// RTP breakdowns are estimated from published total RTP and
// known feature structures where exact splits are not public.
// ============================================================

import { GameConcept, RtpBreakdown, WinDistribution, Feature } from "@/lib/simulation";

// ── Validation-specific metadata (not part of GameConcept) ──

export interface KnownOutcomes {
  // Market reality
  marketPresence: "High" | "Medium" | "Low";
  targetMarkets: string[];
  estimatedSessionLengthMinutes: number;   // typical player session
  sessionProfile: "Short" | "Medium" | "Long";

  // Player behaviour (known from industry data / player communities)
  primaryArchetype: string;       // dominant player type attracted
  secondaryArchetype: string;     // secondary player type
  archetypeReason: string;        // why this archetype dominates

  // Accuracy tracking fields
  launchIndexPredictedArchetype?: string;    // filled in after running simulation
  archetypePredictionCorrect?: boolean;      // filled in after comparison
  sessionPredictionDeltaMinutes?: number;    // predicted - actual

  // Context
  knownStrengths: string[];        // what the game does well commercially
  knownWeaknesses: string[];       // documented commercial weaknesses
  notes: string;
}

export interface ValidationEntry {
  // Identity
  gameName: string;
  provider: string;
  releaseYear: number;

  // Full GameConcept — all fields that match the LaunchIndex form
  gameConcept: GameConcept;

  // What we know happened in the market
  knownOutcomes: KnownOutcomes;
}

// ── Helpers ──────────────────────────────────────────────────

function makeFeature(
  name: string,
  type: string,
  triggerFrequency: string,
  averageValue: number,
  maxValue: number,
  featureVolatility: "Low" | "Medium" | "High"
): Feature {
  return {
    id: name.toLowerCase().replace(/\s+/g, "-"),
    type,
    name,
    triggerCondition: "3+ Scatter symbols",
    triggerFrequency,
    averageValue,
    maxValue,
    featureVolatility,
    visibility: "",
    winImpact: "",
    progressImpact: "",
  };
}

// ── Dataset ──────────────────────────────────────────────────

export const VALIDATION_DATASET: ValidationEntry[] = [

  // ─────────────────────────────────────────────────────────────
  // 1. SWEET BONANZA — Pragmatic Play (2019)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Sweet Bonanza",
    provider: "Pragmatic Play",
    releaseYear: 2019,
    gameConcept: {
      gameName: "Sweet Bonanza",
      targetMarkets: ["UK", "EU", "Global"],
      playerFocus: ["Casual", "Bonus-Seeking"],
      gridLayout: "6×5",
      gridRows: 5,
      gridColumns: 6,
      gameType: "Cluster Pays",
      waysOrLines: 0,
      payStructure: "Cluster",
      cascades: "Yes",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 100",
      volatility: "High",
      rtpTarget: 96.51,
      topWin: 21175,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 33.8,
        wildRtp: 0,
        respinRtp: 0,
        freeSpinsRtp: 55.2,
        jackpotRtp: 0,
        otherFeatureRtp: 7.51,
      },
      winDistribution: {
        sub1x: 38, x1to5: 32, x5to20: 16, x20to100: 9, x100plus: 5,
      },
      features: [
        makeFeature("Free Spins with Multipliers", "Free Spins", "1 in 100", 85, 2000, "High"),
        makeFeature("Ante Bet", "Bonus Buy Entry", "1 in 50", 85, 2000, "High"),
      ],
      baseGameStrength: "Weak (feature-driven)",
      averageBaseWin: 0.55,
      deadSpinFrequency: "Medium",
      targetBankroll: "Medium",
      targetSessionLength: 12,
      specialMechanics: ["Cascades", "Multiplier Symbols", "Bonus Buy", "Ante Bet"],
      primaryGoal: "Big win excitement",
      targetAudience: "Bonus seekers",
      sessionLength: "Medium",
      bonusImportance: "Core",
      earlyExcitement: "Moderate",
      reelType: "Video",
      minClusterSize: 8,
      hasWild: false,
      hasScatter: true,
      scatterThreshold: 4,
      hasRetrigger: false,
      freeSpinCount: 10,
      freeGameReels: "Different reels",
      hasMultiplierSymbol: true,
      multiplierSymbolType: "Spin multiplier",
      bonusBuyAvailable: true,
      anteBetAvailable: true,
      winPacing: "Bonus-dependent",
      requiresSimulation: true,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU", "LATAM", "Global"],
      estimatedSessionLengthMinutes: 11,
      sessionProfile: "Medium",
      primaryArchetype: "Bonus-Seeking Player",
      secondaryArchetype: "Casual Player",
      archetypeReason: "Candy theme drives casual attraction but 96% of excitement is concentrated in the free spins multiplier bomb feature. Players largely spin and wait for the feature, matching Bonus-Seeking behaviour.",
      knownStrengths: [
        "Accessible candy theme appeals to casual and female demographics",
        "Free spins multiplier bombs create extreme variance and viral 'big win' moments",
        "Bonus Buy drives high GGR from bonus seekers willing to pay for direct access",
        "One of the most-streamed slots globally — strong earned media",
      ],
      knownWeaknesses: [
        "Base game is weak — minimal engagement between feature triggers",
        "High feature dependency means cold streaks feel punishing",
        "Very saturated cluster pays segment",
      ],
      notes: "Released 2019, became Pragmatic Play's highest-earning title. 96.51% RTP with Ante Bet available. Top win 21,175× bet. Free spins triggered by 4+ scatter symbols anywhere. Multiplier bombs land in free spins only. Cascading base game with 8+ symbols forming a cluster.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 2. GATES OF OLYMPUS — Pragmatic Play (2021)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Gates of Olympus",
    provider: "Pragmatic Play",
    releaseYear: 2021,
    gameConcept: {
      gameName: "Gates of Olympus",
      targetMarkets: ["UK", "EU", "LATAM", "Global"],
      playerFocus: ["Volatility-Seeking", "Bonus-Seeking"],
      gridLayout: "6×5",
      gridRows: 5,
      gridColumns: 6,
      gameType: "Cluster Pays",
      waysOrLines: 0,
      payStructure: "Cluster",
      cascades: "Yes",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 100",
      volatility: "Very High",
      rtpTarget: 96.5,
      topWin: 5000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 30.2,
        wildRtp: 0,
        respinRtp: 0,
        freeSpinsRtp: 58.8,
        jackpotRtp: 0,
        otherFeatureRtp: 7.5,
      },
      winDistribution: {
        sub1x: 42, x1to5: 30, x5to20: 14, x20to100: 9, x100plus: 5,
      },
      features: [
        makeFeature("Free Spins (Tumble)", "Free Spins", "1 in 100", 75, 5000, "High"),
      ],
      baseGameStrength: "Weak (feature-driven)",
      averageBaseWin: 0.45,
      deadSpinFrequency: "Medium",
      targetBankroll: "Medium",
      targetSessionLength: 10,
      specialMechanics: ["Cascades", "Multiplier Symbols", "Bonus Buy", "Ante Bet"],
      primaryGoal: "Big win excitement",
      targetAudience: "High volatility players",
      sessionLength: "Short",
      bonusImportance: "Core",
      earlyExcitement: "Moderate",
      reelType: "Video",
      minClusterSize: 8,
      hasWild: false,
      hasScatter: true,
      scatterThreshold: 4,
      hasRetrigger: false,
      freeSpinCount: 15,
      freeGameReels: "Same as base game",
      hasMultiplierSymbol: true,
      multiplierSymbolType: "Spin multiplier",
      bonusBuyAvailable: true,
      anteBetAvailable: true,
      winPacing: "Bonus-dependent",
      requiresSimulation: true,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU", "LATAM", "Global"],
      estimatedSessionLengthMinutes: 9,
      sessionProfile: "Short",
      primaryArchetype: "Volatility-Seeking Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "Zeus/Olympus mythology + Very High volatility + 5,000× top win through tumble multiplier accumulation is pure volatility-seeking territory. Streamers and big win hunters dominate player profile.",
      knownStrengths: [
        "Premium Greek mythology theme with strong visual identity",
        "Tumble multipliers can accumulate to extreme levels in free spins",
        "Became the single highest-earning Pragmatic Play title post-2021",
        "Bonus Buy and Ante Bet serve the impatient, high-stakes demographic",
      ],
      knownWeaknesses: [
        "Extremely feature-dependent — base game holds almost no value",
        "Very High volatility means most player sessions end without the big win",
        "Short session lengths reduce D7 retention",
      ],
      notes: "Released 2021. Tumble/cascade mechanic. Scatter symbols (Zeus hands) trigger free spins. During free spins, multiplier symbols add to a global multiplier that applies to all wins. This is the key differentiator from Sweet Bonanza — multipliers accumulate rather than being applied per win.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 3. BOOK OF DEAD — Play'n GO (2016)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Book of Dead",
    provider: "Play'n GO",
    releaseYear: 2016,
    gameConcept: {
      gameName: "Book of Dead",
      targetMarkets: ["UK", "EU", "Nordics"],
      playerFocus: ["Volatility-Seeking", "Bonus-Seeking"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 10,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 150",
      volatility: "High",
      rtpTarget: 96.21,
      topWin: 5000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 42.1,
        wildRtp: 3.5,
        respinRtp: 0,
        freeSpinsRtp: 47.11,
        jackpotRtp: 0,
        otherFeatureRtp: 3.5,
      },
      winDistribution: {
        sub1x: 45, x1to5: 28, x5to20: 13, x20to100: 9, x100plus: 5,
      },
      features: [
        makeFeature("Free Spins (Expanding Symbol)", "Free Spins", "1 in 150", 100, 5000, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.75,
      deadSpinFrequency: "Medium",
      targetBankroll: "Medium",
      targetSessionLength: 14,
      specialMechanics: ["Expanding Wilds"],
      primaryGoal: "Big win excitement",
      targetAudience: "High volatility players",
      sessionLength: "Medium",
      bonusImportance: "Core",
      earlyExcitement: "Moderate",
      reelType: "Video",
      paylineCount: 10,
      hasWild: true,
      wildType: "Expanding",
      expandingWildScope: "Free game only",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: true,
      retriggerFrequency: "1 in 200",
      freeSpinCount: 10,
      freeGameReels: "Same as base game",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Bonus-dependent",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU", "Nordics"],
      estimatedSessionLengthMinutes: 14,
      sessionProfile: "Medium",
      primaryArchetype: "Volatility-Seeking Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "10-payline game where a single expanding symbol can fill all 3 rows on all 5 reels for 5,000× top win. This all-or-nothing free spins mechanic is the definition of volatility-seeking. The Book (wild + scatter) creates strong base game engagement while waiting.",
      knownStrengths: [
        "Book mechanic (wild + scatter) is extremely well-understood by players",
        "Egypt theme has evergreen appeal across markets",
        "Expanding symbol free spins create genuinely dramatic moments",
        "One of the most operator-stocked games ever — near-universal availability",
      ],
      knownWeaknesses: [
        "Theme is heavily saturated — dozens of Book clones",
        "No bonus buy (legacy design) limits GGR potential vs newer titles",
        "Base game is quite dry — 10 paylines means many non-winning spins",
      ],
      notes: "Released 2016. 10 paylines, 5×3, standard Book mechanic. The Book symbol acts as both Wild and Scatter. 3+ scatters trigger 10 free spins. Before free spins, a random symbol is chosen — it expands to fill entire reels when it forms any part of a winning line. Top win requires expanded symbol to pay on all 10 paylines simultaneously.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 4. STARBURST — NetEnt (2012)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Starburst",
    provider: "NetEnt",
    releaseYear: 2012,
    gameConcept: {
      gameName: "Starburst",
      targetMarkets: ["UK", "EU", "Global"],
      playerFocus: ["Casual"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 10,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 75",
      volatility: "Low",
      rtpTarget: 96.09,
      topWin: 500,
      maxExposureCategory: "<500×",
      rtpBreakdown: {
        baseGameRtp: 76.09,
        wildRtp: 12.0,
        respinRtp: 8.0,
        freeSpinsRtp: 0,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 22, x1to5: 52, x5to20: 20, x20to100: 5, x100plus: 1,
      },
      features: [
        makeFeature("Starburst Wild Respins", "Respins", "1 in 75", 4, 50, "Low"),
      ],
      baseGameStrength: "Strong",
      averageBaseWin: 1.2,
      deadSpinFrequency: "Low",
      targetBankroll: "Low",
      targetSessionLength: 30,
      specialMechanics: ["Expanding Wilds"],
      primaryGoal: "High engagement",
      targetAudience: "Casual",
      sessionLength: "Long",
      bonusImportance: "Decorative",
      earlyExcitement: "High",
      reelType: "Video",
      paylineCount: 10,
      hasWild: true,
      wildType: "Expanding",
      expandingWildScope: "All reels",
      hasScatter: false,
      hasRetrigger: false,
      freeSpinCount: 3,
      freeGameReels: "Same as base game",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Front-loaded",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU", "Global"],
      estimatedSessionLengthMinutes: 32,
      sessionProfile: "Long",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Budget Player",
      archetypeReason: "Low volatility, both-ways pays, expanding wild respins, 500× maximum win. The game is designed for sustained engagement rather than big wins. Most frequently used as a welcome bonus wagering vehicle because of its predictable return pattern.",
      knownStrengths: [
        "Longest-running casino staple — still in virtually every operator lobby 12+ years later",
        "No feature complexity = zero learning curve, perfect for new players",
        "Both-ways pays on 10 lines creates surprisingly frequent wins",
        "Expanding wild respins provide excitement without volatility",
      ],
      knownWeaknesses: [
        "500× top win makes it uninteresting for any non-casual player",
        "No free spins means no aspirational peak moment",
        "New player acquisition limited — younger demographics prefer higher variance",
      ],
      notes: "Released 2012. Pays both ways on 10 paylines. Wild (Starburst symbol) expands to fill the reel and triggers up to 3 re-spins. No scatter symbol, no free spins feature. The single feature is the wild respin. This is the definitive example of a base-game-strength-first design where 76%+ of RTP is in the base game.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 5. DEAD OR ALIVE 2 — NetEnt (2019)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Dead or Alive 2",
    provider: "NetEnt",
    releaseYear: 2019,
    gameConcept: {
      gameName: "Dead or Alive 2",
      targetMarkets: ["UK", "Nordics", "EU"],
      playerFocus: ["Volatility-Seeking"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 9,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Low",
      baseHitFrequencyDetail: "Low (<20%)",
      featureTriggerFrequency: "1 in 150",
      volatility: "Very High",
      rtpTarget: 96.8,
      topWin: 100000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 28.0,
        wildRtp: 4.8,
        respinRtp: 0,
        freeSpinsRtp: 64.0,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 55, x1to5: 20, x5to20: 10, x20to100: 8, x100plus: 7,
      },
      features: [
        makeFeature("Train Heist Free Spins (Sticky Wilds)", "Free Spins", "1 in 150", 200, 100000, "High"),
        makeFeature("High Noon Saloon (Walking Wilds)", "Free Spins", "1 in 150", 150, 50000, "High"),
        makeFeature("Old Saloon (Standard Free Spins)", "Free Spins", "1 in 150", 80, 20000, "Medium"),
      ],
      baseGameStrength: "Weak (feature-driven)",
      averageBaseWin: 0.4,
      deadSpinFrequency: "High",
      targetBankroll: "High",
      targetSessionLength: 8,
      specialMechanics: ["Sticky Wilds", "Expanding Wilds"],
      primaryGoal: "Big win excitement",
      targetAudience: "High volatility players",
      sessionLength: "Short",
      bonusImportance: "Core",
      earlyExcitement: "Low",
      reelType: "Video",
      paylineCount: 9,
      hasWild: true,
      wildType: "Sticky",
      stickyWildMode: "Until end of feature",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: false,
      freeSpinCount: 12,
      freeGameReels: "Different reels",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Bonus-dependent",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "Nordics", "EU"],
      estimatedSessionLengthMinutes: 7,
      sessionProfile: "Short",
      primaryArchetype: "Volatility-Seeking Player",
      secondaryArchetype: "Volatility-Seeking Player",
      archetypeReason: "100,000× top win via sticky wild accumulation in free spins. 9 paylines means most spins miss entirely. This is the purest example of a volatility-seeking game in the dataset — almost entirely feature-dependent with extremely low base hit frequency (~17%).",
      knownStrengths: [
        "100,000× top win gives it legendary status among high-volatility players",
        "Three distinct free spins modes add meaningful choice and replay value",
        "Strong aesthetic identity — Western theme with excellent execution",
        "Sticky wilds in Train Heist mode can fill entire screen for maximum win",
      ],
      knownWeaknesses: [
        "Extremely hostile to any non-volatility-seeking player type",
        "Very low hit frequency means long dry periods between any wins",
        "No bonus buy option limits revenue from impatient players",
        "Short typical sessions reduce retention metrics",
      ],
      notes: "Released 2019. 9 paylines, 5×3. Three free spins modes chosen by player: Old Saloon (12 spins, multipliers), High Noon Saloon (12 spins, walking wilds), Train Heist (12 spins, sticky wilds). Train Heist is the highest-volatility mode — sticky wilds accumulate across spins, allowing potentially all positions to become wild on final spin. RTP 96.8% certified.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 6. GONZO'S QUEST — NetEnt (2011)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Gonzo's Quest",
    provider: "NetEnt",
    releaseYear: 2011,
    gameConcept: {
      gameName: "Gonzo's Quest",
      targetMarkets: ["UK", "EU", "Global"],
      playerFocus: ["Casual", "Bonus-Seeking"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 20,
      payStructure: "Lines",
      cascades: "Yes",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 100",
      volatility: "Medium",
      rtpTarget: 95.97,
      topWin: 2500,
      maxExposureCategory: "500–2000×",
      rtpBreakdown: {
        baseGameRtp: 54.0,
        wildRtp: 5.0,
        respinRtp: 0,
        freeSpinsRtp: 35.97,
        jackpotRtp: 0,
        otherFeatureRtp: 1.0,
      },
      winDistribution: {
        sub1x: 30, x1to5: 40, x5to20: 18, x20to100: 9, x100plus: 3,
      },
      features: [
        makeFeature("Free Falls (Cascades + 3x Multiplier)", "Free Spins", "1 in 100", 40, 500, "Medium"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.9,
      deadSpinFrequency: "Low",
      targetBankroll: "Medium",
      targetSessionLength: 22,
      specialMechanics: ["Cascades", "Multipliers"],
      primaryGoal: "High engagement",
      targetAudience: "Casual",
      sessionLength: "Long",
      bonusImportance: "Important",
      earlyExcitement: "High",
      reelType: "Video",
      paylineCount: 20,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: false,
      freeSpinCount: 10,
      freeGameReels: "Same as base game",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Even",
      requiresSimulation: true,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU", "Global"],
      estimatedSessionLengthMinutes: 23,
      sessionProfile: "Long",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "Medium volatility, 20 paylines, cascading wins with increasing multipliers (×1→×2→×3→×5 base, up to ×3/×6/×9/×15 in free spins). The cascade mechanic provides steady small hits and engagement throughout the session. Accessible adventure theme with high production value.",
      knownStrengths: [
        "First major slot to use cascading mechanic — first-mover advantage",
        "Indiana Jones-style exploration narrative gives strong theme identity",
        "Increasing cascade multipliers create a natural excitement escalation",
        "Medium volatility gives it broad player appeal across archetypes",
      ],
      knownWeaknesses: [
        "2,500× max win feels low compared to modern high-volatility titles",
        "No bonus buy — legacy design limitation",
        "Free spins feature is relatively simple by today's standards",
      ],
      notes: "Released 2011, still widely available. 20 paylines, 5×3. Avalanche/cascade mechanic: winning symbols explode, new ones fall. Base game: ×1→×2→×3→×5 multiplier per consecutive cascade. Free Falls (10 spins): ×3→×6→×9→×15. One of the highest long-term operator retention scores of any slot game ever made.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 7. BIG BASS BONANZA — Pragmatic Play (2020)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Big Bass Bonanza",
    provider: "Pragmatic Play",
    releaseYear: 2020,
    gameConcept: {
      gameName: "Big Bass Bonanza",
      targetMarkets: ["UK", "EU", "Global"],
      playerFocus: ["Casual", "Bonus-Seeking"],
      gridLayout: "5×4",
      gridRows: 4,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 10,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 100",
      volatility: "High",
      rtpTarget: 96.71,
      topWin: 2100,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 44.0,
        wildRtp: 3.0,
        respinRtp: 0,
        freeSpinsRtp: 47.71,
        jackpotRtp: 0,
        otherFeatureRtp: 2.0,
      },
      winDistribution: {
        sub1x: 40, x1to5: 33, x5to20: 15, x20to100: 9, x100plus: 3,
      },
      features: [
        makeFeature("Free Spins + Collect Mechanic", "Free Spins", "1 in 100", 65, 2100, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.7,
      deadSpinFrequency: "Medium",
      targetBankroll: "Medium",
      targetSessionLength: 14,
      specialMechanics: ["Collection Mechanics"],
      primaryGoal: "Long sessions",
      targetAudience: "Casual",
      sessionLength: "Medium",
      bonusImportance: "Core",
      earlyExcitement: "Moderate",
      reelType: "Video",
      paylineCount: 10,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: true,
      retriggerFrequency: "1 in 200",
      freeSpinCount: 10,
      freeGameReels: "Same as base game",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Even",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU", "Global"],
      estimatedSessionLengthMinutes: 15,
      sessionProfile: "Medium",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "Fishing theme is inherently accessible and male-skewing casual. The collect mechanic in free spins (fisherman symbol collects all fish symbols showing multiplier values) is intuitive and satisfying. 2,100× max win is aspirational but achievable — not alienating.",
      knownStrengths: [
        "Collect mechanic is universally understood and emotionally satisfying",
        "Fishing theme transcends demographics — strong in UK and EU",
        "Spawned one of the most successful game series ever (Big Bass franchise)",
        "Free spins feel rewarding even at lower win amounts",
      ],
      knownWeaknesses: [
        "2,100× top win limits appeal to high-volatility players",
        "No unique mechanic innovation beyond the collect feature",
      ],
      notes: "Released 2020. 10 paylines, 5×4. The fisherman symbol collects all fish symbols on screen during free spins, with each fish showing a random multiplier value. Retriggerable free spins. Became the anchor game for Pragmatic Play's Big Bass franchise, spawning 8+ sequels including Bigger Bass Bonanza, Big Bass Splash, etc.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 8. JAMMIN' JARS — Push Gaming (2018)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Jammin' Jars",
    provider: "Push Gaming",
    releaseYear: 2018,
    gameConcept: {
      gameName: "Jammin' Jars",
      targetMarkets: ["UK", "Nordics", "EU"],
      playerFocus: ["Bonus-Seeking", "Volatility-Seeking"],
      gridLayout: "8×8",
      gridRows: 8,
      gridColumns: 8,
      gameType: "Cluster Pays",
      waysOrLines: 0,
      payStructure: "Cluster",
      cascades: "Yes",
      baseHitFrequency: "High",
      baseHitFrequencyDetail: "High (>35%)",
      featureTriggerFrequency: "1 in 100",
      volatility: "High",
      rtpTarget: 96.83,
      topWin: 20000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 38.0,
        wildRtp: 8.0,
        respinRtp: 0,
        freeSpinsRtp: 48.83,
        jackpotRtp: 0,
        otherFeatureRtp: 2.0,
      },
      winDistribution: {
        sub1x: 28, x1to5: 35, x5to20: 20, x20to100: 12, x100plus: 5,
      },
      features: [
        makeFeature("Free Spins + Rainbow Wild", "Free Spins", "1 in 100", 95, 20000, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.85,
      deadSpinFrequency: "Low",
      targetBankroll: "Medium",
      targetSessionLength: 14,
      specialMechanics: ["Cascades", "Expanding Wilds", "Multiplier Symbols"],
      primaryGoal: "High engagement",
      targetAudience: "Bonus seekers",
      sessionLength: "Medium",
      bonusImportance: "Core",
      earlyExcitement: "High",
      reelType: "Video",
      minClusterSize: 5,
      hasWild: true,
      wildType: "Expanding",
      expandingWildScope: "Free game only",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: false,
      freeSpinCount: 10,
      freeGameReels: "Same as base game",
      hasMultiplierSymbol: true,
      multiplierSymbolType: "Progressive (adds each cascade)",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Bonus-dependent",
      requiresSimulation: true,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "Nordics", "EU"],
      estimatedSessionLengthMinutes: 13,
      sessionProfile: "Medium",
      primaryArchetype: "Bonus-Seeking Player",
      secondaryArchetype: "Volatility-Seeking Player",
      archetypeReason: "8×8 cluster grid creates high visual activity and frequent small wins in base game, but 20,000× top win potential is driven entirely by the Rainbow Wild expanding across the grid in free spins. Players stay for the base game but hunt for the feature.",
      knownStrengths: [
        "8×8 grid creates more frequent cluster hits than smaller grid designs",
        "Rainbow Wild mechanic is visually spectacular and mechanically distinct",
        "High base game engagement reduces early-session churn",
        "Retro fruit + rainbow aesthetic has enduring visual appeal",
      ],
      knownWeaknesses: [
        "Complex grid cluster pays can confuse casual players",
        "Top wins require very specific free spins conditions — rare",
      ],
      notes: "Released 2018. 8×8 grid, cluster pays (5+ adjacent symbols). Base game has random Rainbow Wild scatter that moves and grows during tumble sequences. Free spins (3+ scatter triggers): Rainbow Wild starts small and grows with each cascade, applying multipliers. Spawned Jammin' Jars 2 (2021) with 50,000× top win.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 9. WOLF GOLD — Pragmatic Play (2017)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Wolf Gold",
    provider: "Pragmatic Play",
    releaseYear: 2017,
    gameConcept: {
      gameName: "Wolf Gold",
      targetMarkets: ["Global"],
      playerFocus: ["Casual", "Bonus-Seeking"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 25,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 100",
      volatility: "Medium",
      rtpTarget: 96.01,
      topWin: 5000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 50.0,
        wildRtp: 4.0,
        respinRtp: 20.0,
        freeSpinsRtp: 18.01,
        jackpotRtp: 4.0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 35, x1to5: 38, x5to20: 16, x20to100: 8, x100plus: 3,
      },
      features: [
        makeFeature("Free Spins", "Free Spins", "1 in 100", 50, 500, "Medium"),
        makeFeature("Money Respin (Hold & Spin)", "Respins", "1 in 75", 40, 5000, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.85,
      deadSpinFrequency: "Low",
      targetBankroll: "Medium",
      targetSessionLength: 20,
      specialMechanics: ["Progressive Jackpot", "Collection Mechanics"],
      primaryGoal: "High engagement",
      targetAudience: "Casual",
      sessionLength: "Long",
      bonusImportance: "Important",
      earlyExcitement: "Moderate",
      reelType: "Video",
      paylineCount: 25,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: false,
      freeSpinCount: 5,
      freeGameReels: "Different reels",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Even",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["Global"],
      estimatedSessionLengthMinutes: 21,
      sessionProfile: "Long",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "Medium volatility, 25 paylines, two distinct features (free spins + money respin), progressive jackpot. Three-tier jackpot system (Mini/Minor/Major) provides aspirational value without extreme volatility. The money respin hold & spin feature is accessible and frequent.",
      knownStrengths: [
        "Two distinct features (free spins + Hold & Spin) keep variety high",
        "Progressive jackpot adds aspirational layer for all player types",
        "Medium volatility + 25 paylines = frequent wins for casual retention",
        "Globally appealing wolf/western theme",
      ],
      knownWeaknesses: [
        "Jackpot RTP dilutes base game value perception",
        "Becoming dated relative to newer multi-mechanic titles",
      ],
      notes: "Released 2017. 25 paylines, 5×3. Two feature modes: Free Spins (3 scatters, giant symbols on reels 2/3/4 during free spins) and Money Respin (6 money symbols triggers Hold & Spin with 3 respins and progressive jackpot). One of Pragmatic Play's longest-running highest-availability games.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 10. BONANZA MEGAWAYS — Big Time Gaming (2016)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Bonanza Megaways",
    provider: "Big Time Gaming",
    releaseYear: 2016,
    gameConcept: {
      gameName: "Bonanza Megaways",
      targetMarkets: ["UK", "EU", "Global"],
      playerFocus: ["Volatility-Seeking", "Bonus-Seeking"],
      gridLayout: "6×2-7",
      gridRows: 7,
      gridColumns: 6,
      gameType: "Megaways",
      waysOrLines: 117649,
      payStructure: "Ways",
      cascades: "Yes",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 150",
      volatility: "Very High",
      rtpTarget: 96.0,
      topWin: 10000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 30.0,
        wildRtp: 2.0,
        respinRtp: 0,
        freeSpinsRtp: 64.0,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 45, x1to5: 26, x5to20: 13, x20to100: 10, x100plus: 6,
      },
      features: [
        makeFeature("Free Spins (Unlimited Multiplier)", "Free Spins", "1 in 150", 120, 10000, "High"),
      ],
      baseGameStrength: "Weak (feature-driven)",
      averageBaseWin: 0.45,
      deadSpinFrequency: "Medium",
      targetBankroll: "High",
      targetSessionLength: 10,
      specialMechanics: ["Cascades", "Megaways", "Ante Bet"],
      primaryGoal: "Big win excitement",
      targetAudience: "High volatility players",
      sessionLength: "Short",
      bonusImportance: "Core",
      earlyExcitement: "Moderate",
      reelType: "Video",
      megawaysMaxWays: 117649,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 4,
      hasRetrigger: false,
      freeSpinCount: 12,
      freeGameReels: "Same as base game",
      anteBetAvailable: true,
      bonusBuyAvailable: false,
      winPacing: "Bonus-dependent",
      requiresSimulation: true,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU", "Global"],
      estimatedSessionLengthMinutes: 9,
      sessionProfile: "Short",
      primaryArchetype: "Volatility-Seeking Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "The original Megaways game. Up to 117,649 ways, cascading wins, unlimited free spins multiplier (starts at ×1, increases by 1 with every cascade — can reach ×50+). The entire game is designed around the free spins multiplier. Extreme variance.",
      knownStrengths: [
        "Invented the Megaways mechanic — permanent historical significance",
        "Unlimited multiplier creates genuinely unpredictable win potential",
        "4 gold mine scatters across top bar and 5 reels creates anticipation throughout",
        "Licensed Megaways mechanic spawned hundreds of follow-on titles",
      ],
      knownWeaknesses: [
        "Base game is underpowered — variable ways with low base hit rate",
        "Very high variance means most bonus buys feel unsatisfying",
        "Feature frequency (1 in 150) is low relative to session lengths",
      ],
      notes: "Released 2016. The original Megaways slot. 6 reels with 2–7 symbols each (variable per spin, driven by top horizontal reel showing gold mine symbols). Up to 117,649 ways. Free Spins: unlimited spins, multiplier +1 per cascade. Has since been replicated by 300+ licensed Megaways titles.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 11. REACTOONZ — Play'n GO (2017)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Reactoonz",
    provider: "Play'n GO",
    releaseYear: 2017,
    gameConcept: {
      gameName: "Reactoonz",
      targetMarkets: ["Nordics", "UK", "EU"],
      playerFocus: ["Bonus-Seeking", "Casual"],
      gridLayout: "7×7",
      gridRows: 7,
      gridColumns: 7,
      gameType: "Cluster Pays",
      waysOrLines: 0,
      payStructure: "Cluster",
      cascades: "Yes",
      baseHitFrequency: "High",
      baseHitFrequencyDetail: "High (>35%)",
      featureTriggerFrequency: "1 in 75",
      volatility: "High",
      rtpTarget: 96.51,
      topWin: 4570,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 40.0,
        wildRtp: 5.0,
        respinRtp: 0,
        freeSpinsRtp: 0,
        jackpotRtp: 0,
        otherFeatureRtp: 51.51,
      },
      winDistribution: {
        sub1x: 25, x1to5: 40, x5to20: 22, x20to100: 10, x100plus: 3,
      },
      features: [
        makeFeature("Quantum Features (Gargantoon, Implosion, Demolition, Alteration)", "Cascading Mode", "1 in 75", 55, 4570, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.8,
      deadSpinFrequency: "Low",
      targetBankroll: "Medium",
      targetSessionLength: 16,
      specialMechanics: ["Cascades", "Collection Mechanics", "Multiplier Symbols"],
      primaryGoal: "High engagement",
      targetAudience: "Casual",
      sessionLength: "Medium",
      bonusImportance: "Core",
      earlyExcitement: "High",
      reelType: "Video",
      minClusterSize: 5,
      hasWild: true,
      wildType: "Multiplier",
      multiplierWildValueType: "Random",
      hasScatter: false,
      hasRetrigger: false,
      hasMultiplierSymbol: true,
      multiplierSymbolType: "Win multiplier",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Even",
      requiresSimulation: true,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["Nordics", "UK", "EU"],
      estimatedSessionLengthMinutes: 16,
      sessionProfile: "Medium",
      primaryArchetype: "Bonus-Seeking Player",
      secondaryArchetype: "Casual Player",
      archetypeReason: "7×7 cluster grid with cascading symbols and a charge meter (Quantumeter) that fills with each cascade and triggers one of four Quantum Features. No traditional scatter/free spins — the entire feature layer is driven by the progressive meter. Highly engaging for bonus seekers who can see progress building.",
      knownStrengths: [
        "7×7 grid creates very high hit frequency — low dead spin rate",
        "Quantumeter provides persistent visual progress indicator reducing frustration",
        "Alien creature theme with unique visual identity — highly memorable",
        "Four distinct Quantum Features provide strong variety",
      ],
      knownWeaknesses: [
        "No traditional free spins — some players find this disorienting",
        "Feature delivery is gradual rather than peak-and-trough — less streamer appeal",
      ],
      notes: "Released 2017. 7×7 cluster grid (5+ adjacent symbols pay). Cascades fill the Quantumeter, which triggers: Implosion (destroys low-pay symbols), Alteration (transforms one symbol type), Demolition (destroys all of one symbol), Gargantoon (drops a giant 3×3 wild). No traditional scatter. Has Gargantoon symbol that acts as roaming wild between features.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 12. FIRE JOKER — Play'n GO (2016)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Fire Joker",
    provider: "Play'n GO",
    releaseYear: 2016,
    gameConcept: {
      gameName: "Fire Joker",
      targetMarkets: ["Nordics", "EU"],
      playerFocus: ["Casual"],
      gridLayout: "3×3",
      gridRows: 3,
      gridColumns: 3,
      gameType: "Paylines",
      waysOrLines: 5,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 75",
      volatility: "High",
      rtpTarget: 96.15,
      topWin: 800,
      maxExposureCategory: "500–2000×",
      rtpBreakdown: {
        baseGameRtp: 55.0,
        wildRtp: 5.0,
        respinRtp: 33.15,
        freeSpinsRtp: 0,
        jackpotRtp: 0,
        otherFeatureRtp: 3.0,
      },
      winDistribution: {
        sub1x: 28, x1to5: 44, x5to20: 20, x20to100: 7, x100plus: 1,
      },
      features: [
        makeFeature("Wheel of Multipliers Respin", "Respins", "1 in 75", 15, 120, "Medium"),
      ],
      baseGameStrength: "Strong",
      averageBaseWin: 1.1,
      deadSpinFrequency: "Low",
      targetBankroll: "Low",
      targetSessionLength: 25,
      specialMechanics: [],
      primaryGoal: "High engagement",
      targetAudience: "Casual",
      sessionLength: "Long",
      bonusImportance: "Decorative",
      earlyExcitement: "High",
      reelType: "Video",
      paylineCount: 5,
      hasWild: true,
      wildType: "Standard",
      hasScatter: false,
      hasRetrigger: false,
      freeSpinCount: 0,
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Front-loaded",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "Medium",
      targetMarkets: ["Nordics", "EU"],
      estimatedSessionLengthMinutes: 26,
      sessionProfile: "Long",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Budget Player",
      archetypeReason: "3×3 classic fruit machine format. 5 paylines. High hit frequency for the format. The Wheel of Multipliers respin (triggered when two full reels show the same symbol) is simple, classic, and accessible. 800× max win is reasonable but not aspirational.",
      knownStrengths: [
        "Retro 3×3 format appeals strongly to Scandinavian classic slot preference",
        "Simple mechanic with zero learning curve",
        "High session friendliness due to frequent small wins",
        "Strong in pub-gaming and casual player segments",
      ],
      knownWeaknesses: [
        "800× max win extremely low — no volatility seeking appeal at all",
        "No free spins — younger players expect a feature mode",
        "Limited market — primarily Nordic/EU classic slot audience",
      ],
      notes: "Released 2016. 3×3 grid, 5 paylines. Classic fruit symbols (cherries, lemons, oranges, plums, bars, 7s) plus Joker wild. Feature: when two full reels (all 3 positions) show the same symbol, the Wheel of Multipliers is triggered and a multiplier applied to the respin. Very short session variance — suitable for low-bankroll play.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 13. FISHIN' FRENZY — Blueprint Gaming (2015)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Fishin' Frenzy",
    provider: "Blueprint Gaming",
    releaseYear: 2015,
    gameConcept: {
      gameName: "Fishin' Frenzy",
      targetMarkets: ["UK"],
      playerFocus: ["Casual", "Budget-Constrained"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 10,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "High",
      baseHitFrequencyDetail: "High (>35%)",
      featureTriggerFrequency: "1 in 75",
      volatility: "Low",
      rtpTarget: 95.4,
      topWin: 500,
      maxExposureCategory: "<500×",
      rtpBreakdown: {
        baseGameRtp: 68.4,
        wildRtp: 5.0,
        respinRtp: 0,
        freeSpinsRtp: 22.0,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 15, x1to5: 58, x5to20: 20, x20to100: 6, x100plus: 1,
      },
      features: [
        makeFeature("Free Spins + Fisherman Collect", "Free Spins", "1 in 75", 20, 250, "Low"),
      ],
      baseGameStrength: "Strong",
      averageBaseWin: 1.3,
      deadSpinFrequency: "Low",
      targetBankroll: "Low",
      targetSessionLength: 35,
      specialMechanics: ["Collection Mechanics"],
      primaryGoal: "Long sessions",
      targetAudience: "Casual",
      sessionLength: "Long",
      bonusImportance: "Decorative",
      earlyExcitement: "High",
      reelType: "Video",
      paylineCount: 10,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: true,
      retriggerFrequency: "1 in 200",
      freeSpinCount: 10,
      freeGameReels: "Same as base game",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Front-loaded",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK"],
      estimatedSessionLengthMinutes: 37,
      sessionProfile: "Long",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Budget Player",
      archetypeReason: "UK pub/arcade heritage. Low volatility, high hit frequency, collect mechanic in free spins. The fisherman collects values shown on fish symbols — satisfying, simple, completely non-threatening. 500× max win means low bankroll risk. Extremely long typical sessions.",
      knownStrengths: [
        "Highest session length in dataset — exceptional retention",
        "UK pub gaming heritage gives it deep cultural familiarity",
        "Collect mechanic is immediately intuitive",
        "One of Blueprint's best-performing long-tail titles",
      ],
      knownWeaknesses: [
        "500× max win makes it invisible to any non-casual player",
        "Almost exclusively UK market — no international crossover",
        "95.4% RTP lower than modern competition",
      ],
      notes: "Released 2015. 10 paylines, 5×3. The UK fishing collect mechanic archetype. Fisherman symbol (scatter) triggers free spins and during free spins collects the cash values shown on fish symbols on the screen. Multiplier applied to total collected amount. Spawned Fishin' Frenzy Megaways, The Big Catch, and numerous follow-ons.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 14. THE DOG HOUSE — Pragmatic Play (2019)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "The Dog House",
    provider: "Pragmatic Play",
    releaseYear: 2019,
    gameConcept: {
      gameName: "The Dog House",
      targetMarkets: ["UK", "EU", "Global"],
      playerFocus: ["Casual", "Bonus-Seeking"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 20,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 100",
      volatility: "High",
      rtpTarget: 96.51,
      topWin: 6750,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 43.0,
        wildRtp: 4.5,
        respinRtp: 0,
        freeSpinsRtp: 49.01,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 40, x1to5: 32, x5to20: 15, x20to100: 9, x100plus: 4,
      },
      features: [
        makeFeature("Free Spins + Sticky Wild Multipliers", "Free Spins", "1 in 100", 70, 6750, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.72,
      deadSpinFrequency: "Medium",
      targetBankroll: "Medium",
      targetSessionLength: 13,
      specialMechanics: ["Sticky Wilds", "Multiplier Symbols"],
      primaryGoal: "High engagement",
      targetAudience: "Casual",
      sessionLength: "Medium",
      bonusImportance: "Core",
      earlyExcitement: "Moderate",
      reelType: "Video",
      paylineCount: 20,
      hasWild: true,
      wildType: "Sticky + Multiplier",
      stickyWildMode: "Until end of feature",
      multiplierWildValueType: "Random",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: true,
      retriggerFrequency: "1 in 200",
      freeSpinCount: 10,
      freeGameReels: "Different reels",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Even",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU", "Global"],
      estimatedSessionLengthMinutes: 14,
      sessionProfile: "Medium",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "Dog theme is universally appealing, particularly to casual and female demographics. 20 paylines with sticky wild multipliers (2× or 3×) in free spins creates accessible excitement. 6,750× top win requires multiple multiplier wilds on same lines — achievable but not extreme.",
      knownStrengths: [
        "Dog theme has broad demographic appeal including female player segment",
        "Sticky wild multipliers in free spins feel impactful without being overcomplicated",
        "20 paylines with 5×3 grid = good frequency for casual retention",
        "Spawned The Dog House Megaways — franchise building capability",
      ],
      knownWeaknesses: [
        "Nothing mechanically unique — sticky wilds are well-established",
        "Feature dependency is moderate-high, making base game less engaging",
      ],
      notes: "Released 2019. 20 paylines, 5×3. During free spins, wild symbols are sticky AND carry a multiplier (2× or 3× randomly assigned). All sticky wilds remain until end of feature. Multipliers stack multiplicatively when a line contains multiple sticky wilds. Retrigger available.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 15. LEGACY OF DEAD — Play'n GO (2020)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Legacy of Dead",
    provider: "Play'n GO",
    releaseYear: 2020,
    gameConcept: {
      gameName: "Legacy of Dead",
      targetMarkets: ["UK", "EU"],
      playerFocus: ["Volatility-Seeking"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 10,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 150",
      volatility: "Very High",
      rtpTarget: 96.58,
      topWin: 5000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 38.0,
        wildRtp: 3.5,
        respinRtp: 0,
        freeSpinsRtp: 55.08,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 48, x1to5: 26, x5to20: 12, x20to100: 9, x100plus: 5,
      },
      features: [
        makeFeature("Free Spins (Expanding Symbol)", "Free Spins", "1 in 150", 110, 5000, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.65,
      deadSpinFrequency: "Medium",
      targetBankroll: "High",
      targetSessionLength: 9,
      specialMechanics: ["Expanding Wilds"],
      primaryGoal: "Big win excitement",
      targetAudience: "High volatility players",
      sessionLength: "Short",
      bonusImportance: "Core",
      earlyExcitement: "Low",
      reelType: "Video",
      paylineCount: 10,
      hasWild: true,
      wildType: "Expanding",
      expandingWildScope: "Free game only",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: true,
      retriggerFrequency: "1 in 200",
      freeSpinCount: 10,
      freeGameReels: "Same as base game",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Bonus-dependent",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK", "EU"],
      estimatedSessionLengthMinutes: 9,
      sessionProfile: "Short",
      primaryArchetype: "Volatility-Seeking Player",
      secondaryArchetype: "Volatility-Seeking Player",
      archetypeReason: "Book of Dead successor with higher volatility designation. Same expanding symbol mechanic but more aggressive variance profile. Very High volatility + 10 paylines + feature trigger at 1 in 150 means even more pronounced feast-or-famine sessions than its predecessor.",
      knownStrengths: [
        "Direct successor to Book of Dead — inherits brand recognition",
        "Very High volatility designation attracts hardcore volatility seekers",
        "Egypt theme remains reliable",
        "Strong free spins expansion mechanic",
      ],
      knownWeaknesses: [
        "Essentially Book of Dead with higher volatility — limited differentiation",
        "Very short typical sessions reduce operator retention value",
        "Base game is very dry — long dead spin runs before feature",
      ],
      notes: "Released 2020. 10 paylines, 5×3. Functionally nearly identical to Book of Dead but tuned to Very High volatility. The expanding symbol in free spins mechanic is the same — random symbol expands to fill all positions on its reel. Play'n GO explicitly positioned this as a higher-variance alternative to Book of Dead.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 16. IMMORTAL ROMANCE — Microgaming (2011)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Immortal Romance",
    provider: "Microgaming",
    releaseYear: 2011,
    gameConcept: {
      gameName: "Immortal Romance",
      targetMarkets: ["EU", "Global"],
      playerFocus: ["Casual", "Bonus-Seeking"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Payways",
      waysOrLines: 243,
      payStructure: "Ways",
      cascades: "No",
      baseHitFrequency: "High",
      baseHitFrequencyDetail: "High (>35%)",
      featureTriggerFrequency: "1 in 50",
      volatility: "Medium",
      rtpTarget: 96.86,
      topWin: 3645,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 57.0,
        wildRtp: 5.0,
        respinRtp: 0,
        freeSpinsRtp: 30.86,
        jackpotRtp: 0,
        otherFeatureRtp: 4.0,
      },
      winDistribution: {
        sub1x: 22, x1to5: 48, x5to20: 20, x20to100: 8, x100plus: 2,
      },
      features: [
        makeFeature("Chamber of Spins (4 escalating modes)", "Free Spins", "1 in 50", 45, 3645, "Medium"),
        makeFeature("Wild Desire (random wild reels)", "Respins", "1 in 200", 25, 1000, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 1.05,
      deadSpinFrequency: "Low",
      targetBankroll: "Low",
      targetSessionLength: 28,
      specialMechanics: ["Collection Mechanics"],
      primaryGoal: "Long sessions",
      targetAudience: "Casual",
      sessionLength: "Long",
      bonusImportance: "Important",
      earlyExcitement: "High",
      reelType: "Video",
      waysConstant: 243,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: false,
      freeSpinCount: 10,
      freeGameReels: "Different reels",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Even",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["EU", "Global"],
      estimatedSessionLengthMinutes: 29,
      sessionProfile: "Long",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "Vampire romance narrative with four story characters (Amber, Troy, Michael, Sarah) whose free spins modes unlock progressively. 243 ways creates high base hit frequency. Medium volatility + story progression keeps Casual and Engagement Seeker archetypes highly engaged across long sessions.",
      knownStrengths: [
        "Progressive story structure (unlock better characters with more triggers) is unique engagement loop",
        "243 ways creates high base game hit frequency — very low dead spin rate",
        "Medium volatility with story appeal broadens demographic beyond typical slot players",
        "Wild Desire feature (random full wild reels) provides surprise peaks",
        "Still highly available 13 years after launch — extraordinary longevity",
      ],
      knownWeaknesses: [
        "Story structure is invisible to casual players who don't notice progression",
        "Modern players expect higher top win and volatility",
        "No bonus buy (legacy design)",
      ],
      notes: "Released 2011. 243 ways, 5×3. One of Microgaming's all-time most successful titles. The Chamber of Spins (3 scatters) unlocks progressively: Amber (10 spins + multipliers), Troy (15 spins + multiplier wilds), Michael (20 spins + rolling reels), Sarah (25 spins + wild vine feature). Wild Desire feature: random chance of 1-5 reels turning fully wild during any base spin.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 17. RAINBOW RICHES — Barcrest (2009 / SG Digital 2014 online)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Rainbow Riches",
    provider: "Barcrest / SG Digital",
    releaseYear: 2014,
    gameConcept: {
      gameName: "Rainbow Riches",
      targetMarkets: ["UK"],
      playerFocus: ["Casual", "Budget-Constrained"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 20,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "High",
      baseHitFrequencyDetail: "High (>35%)",
      featureTriggerFrequency: "1 in 75",
      volatility: "Low",
      rtpTarget: 95.0,
      topWin: 500,
      maxExposureCategory: "<500×",
      rtpBreakdown: {
        baseGameRtp: 65.0,
        wildRtp: 3.0,
        respinRtp: 0,
        freeSpinsRtp: 14.0,
        jackpotRtp: 0,
        otherFeatureRtp: 13.0,
      },
      winDistribution: {
        sub1x: 12, x1to5: 60, x5to20: 20, x20to100: 7, x100plus: 1,
      },
      features: [
        makeFeature("Road to Riches (multiplier trail)", "Pick Bonus", "1 in 75", 20, 500, "Low"),
        makeFeature("Wishing Well (cash prizes)", "Pick Bonus", "1 in 100", 12, 200, "Low"),
        makeFeature("Pots of Gold (spinning wheel)", "Pick Bonus", "1 in 100", 15, 200, "Low"),
      ],
      baseGameStrength: "Strong",
      averageBaseWin: 1.4,
      deadSpinFrequency: "Low",
      targetBankroll: "Low",
      targetSessionLength: 40,
      specialMechanics: [],
      primaryGoal: "Long sessions",
      targetAudience: "Casual",
      sessionLength: "Long",
      bonusImportance: "Important",
      earlyExcitement: "High",
      reelType: "Video",
      paylineCount: 20,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: false,
      freeSpinCount: 10,
      freeGameReels: "Same as base game",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Front-loaded",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "High",
      targetMarkets: ["UK"],
      estimatedSessionLengthMinutes: 42,
      sessionProfile: "Long",
      primaryArchetype: "Casual Player",
      secondaryArchetype: "Budget Player",
      archetypeReason: "UK pub gaming icon. Three pick bonus features (Road to Riches multiplier trail, Wishing Well, Pots of Gold) are classic and intuitive. 500× max win, high base hit frequency, low volatility. The quintessential budget player's game — designed for extended low-stakes play.",
      knownStrengths: [
        "Longest session length in the dataset — exceptional casual retention",
        "Three distinct bonus features provide sustained variety",
        "UK cultural icon — decades of brand recognition",
        "20 paylines + strong base game = very low dead spin rate",
      ],
      knownWeaknesses: [
        "Almost exclusively UK market — no international penetration",
        "500× max win provides zero aspirational value for any other player type",
        "95% RTP is below modern competitive benchmark",
        "No free spins mechanic limits streamer/bonus hunter appeal",
      ],
      notes: "Originated as a fruit machine in UK pubs, transitioned online via Barcrest/SG Digital. 20 paylines, 5×3. Three bonus features triggered by leprechaun scatter symbols. Road to Riches is the most popular — a multiplier trail where each spin moves the leprechaun forward, multiplying the stake. The highest session length in any major dataset is a consistent finding for this title.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 18. RAZOR SHARK — Push Gaming (2019)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Razor Shark",
    provider: "Push Gaming",
    releaseYear: 2019,
    gameConcept: {
      gameName: "Razor Shark",
      targetMarkets: ["UK", "Nordics", "EU"],
      playerFocus: ["Volatility-Seeking", "Bonus-Seeking"],
      gridLayout: "5×4",
      gridRows: 4,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 20,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 75",
      volatility: "High",
      rtpTarget: 96.71,
      topWin: 50000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 38.0,
        wildRtp: 4.0,
        respinRtp: 15.71,
        freeSpinsRtp: 39.0,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 42, x1to5: 30, x5to20: 14, x20to100: 9, x100plus: 5,
      },
      features: [
        makeFeature("Free Spins + Nudge Feature", "Free Spins", "1 in 75", 80, 50000, "High"),
        makeFeature("Mystery Stacks (Shark symbols)", "Respins", "1 in 75", 15, 500, "Medium"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.65,
      deadSpinFrequency: "Medium",
      targetBankroll: "Medium",
      targetSessionLength: 11,
      specialMechanics: ["Collection Mechanics", "Multiplier Symbols"],
      primaryGoal: "Big win excitement",
      targetAudience: "High volatility players",
      sessionLength: "Short",
      bonusImportance: "Core",
      earlyExcitement: "Moderate",
      reelType: "Video",
      paylineCount: 20,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: true,
      retriggerFrequency: "1 in 200",
      freeSpinCount: 10,
      freeGameReels: "Different reels",
      hasMultiplierSymbol: true,
      multiplierSymbolType: "Win multiplier",
      bonusBuyAvailable: true,
      anteBetAvailable: false,
      winPacing: "Bonus-dependent",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "Medium",
      targetMarkets: ["UK", "Nordics", "EU"],
      estimatedSessionLengthMinutes: 11,
      sessionProfile: "Short",
      primaryArchetype: "Volatility-Seeking Player",
      secondaryArchetype: "Bonus-Seeking Player",
      archetypeReason: "50,000× top win via mystery shark stacks + free spins multiplier accumulation makes this squarely a volatility-seeker's game. The nudge feature in base game provides frequent dramatic moments as partial mystery stacks can be nudged to complete the reel. Push Gaming's highest-variance offering at time of release.",
      knownStrengths: [
        "50,000× top win places it alongside Dead or Alive 2 in elite variance territory",
        "Nudge mechanic in base game provides near-hit excitement and engagement between features",
        "Mystery shark stacks create visual anticipation on every spin",
        "Bonus buy available — serves impatient high-variance hunters",
      ],
      knownWeaknesses: [
        "Relatively low market penetration vs. similarly-volatility-positioned competitors",
        "Short sessions limit operator retention metrics",
        "Feature dependency very high — base game solo cannot sustain play",
      ],
      notes: "Released 2019. 20 paylines, 5×4. Mystery stacks of Razor Shark symbols can appear on reels. If a mystery stack appears but doesn't fill the full reel, a nudge mechanic can complete it. Free spins: multipliers attached to shark mystery stacks, accumulating across spins. 50,000× top win requires multiple multiplier stacks during free spins.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 19. EXTRA CHILLI — Big Time Gaming (2018)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Extra Chilli",
    provider: "Big Time Gaming",
    releaseYear: 2018,
    gameConcept: {
      gameName: "Extra Chilli",
      targetMarkets: ["UK", "EU"],
      playerFocus: ["Volatility-Seeking"],
      gridLayout: "6×2-7",
      gridRows: 7,
      gridColumns: 6,
      gameType: "Megaways",
      waysOrLines: 117649,
      payStructure: "Ways",
      cascades: "Yes",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 150",
      volatility: "Very High",
      rtpTarget: 96.12,
      topWin: 10000,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 28.0,
        wildRtp: 2.12,
        respinRtp: 0,
        freeSpinsRtp: 66.0,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 48, x1to5: 24, x5to20: 12, x20to100: 10, x100plus: 6,
      },
      features: [
        makeFeature("Free Spins (Unlimited Multiplier, Spice Gamble)", "Free Spins", "1 in 150", 130, 10000, "High"),
      ],
      baseGameStrength: "Weak (feature-driven)",
      averageBaseWin: 0.42,
      deadSpinFrequency: "High",
      targetBankroll: "High",
      targetSessionLength: 8,
      specialMechanics: ["Cascades", "Megaways", "Bonus Buy"],
      primaryGoal: "Big win excitement",
      targetAudience: "High volatility players",
      sessionLength: "Short",
      bonusImportance: "Core",
      earlyExcitement: "Low",
      reelType: "Video",
      megawaysMaxWays: 117649,
      hasWild: true,
      wildType: "Standard",
      hasScatter: true,
      scatterThreshold: 4,
      hasRetrigger: false,
      freeSpinCount: 10,
      freeGameReels: "Same as base game",
      bonusBuyAvailable: true,
      anteBetAvailable: false,
      winPacing: "Bonus-dependent",
      requiresSimulation: true,
    },
    knownOutcomes: {
      marketPresence: "Medium",
      targetMarkets: ["UK", "EU"],
      estimatedSessionLengthMinutes: 8,
      sessionProfile: "Short",
      primaryArchetype: "Volatility-Seeking Player",
      secondaryArchetype: "Volatility-Seeking Player",
      archetypeReason: "Very High volatility Megaways with unlimited free spins multiplier. The Spice Gamble mechanic (gamble collected free spins for more) adds a second layer of volatility-seeking behaviour — high-risk players actively choose to gamble their trigger for potential bigger sessions. Almost exclusively attracts volatility seekers.",
      knownStrengths: [
        "Spice Gamble mechanic adds meaningful player agency to the free spins trigger",
        "10,000× top win via unlimited multiplier accumulation",
        "Bonus Buy enables direct access for impatient volatility seekers",
        "Mexican food theme is visually distinctive and cheerful contrast to the extreme variance",
      ],
      knownWeaknesses: [
        "One of the most feature-dependent games in the dataset (>68% feature RTP)",
        "Very low base hit frequency creates extremely hostile experience between features",
        "Short sessions dramatically reduce operator D7 retention",
        "Very small addressable audience — pure volatility seekers only",
      ],
      notes: "Released 2018. Same Megaways engine as Bonanza but with BTG's Spice Gamble innovation: when free spins are triggered, player can gamble the collected spins (10 base spins) by spinning a chilli to potentially win more spins — or lose some. The gamble feature can theoretically award very large spin counts. Unlimited multiplier accumulates with each cascade during free spins.",
    },
  },

  // ─────────────────────────────────────────────────────────────
  // 20. STICKY BANDITS — Quickspin (2018)
  // ─────────────────────────────────────────────────────────────
  {
    gameName: "Sticky Bandits",
    provider: "Quickspin",
    releaseYear: 2018,
    gameConcept: {
      gameName: "Sticky Bandits",
      targetMarkets: ["EU", "Nordics"],
      playerFocus: ["Bonus-Seeking", "Casual"],
      gridLayout: "5×3",
      gridRows: 3,
      gridColumns: 5,
      gameType: "Paylines",
      waysOrLines: 20,
      payStructure: "Lines",
      cascades: "No",
      baseHitFrequency: "Medium",
      baseHitFrequencyDetail: "Medium (20–35%)",
      featureTriggerFrequency: "1 in 100",
      volatility: "High",
      rtpTarget: 96.6,
      topWin: 3375,
      maxExposureCategory: "2000×+",
      rtpBreakdown: {
        baseGameRtp: 42.0,
        wildRtp: 6.6,
        respinRtp: 0,
        freeSpinsRtp: 48.0,
        jackpotRtp: 0,
        otherFeatureRtp: 0,
      },
      winDistribution: {
        sub1x: 42, x1to5: 32, x5to20: 14, x20to100: 8, x100plus: 4,
      },
      features: [
        makeFeature("Free Spins + Sticky Bandits Collect", "Free Spins", "1 in 100", 75, 3375, "High"),
      ],
      baseGameStrength: "Balanced",
      averageBaseWin: 0.7,
      deadSpinFrequency: "Medium",
      targetBankroll: "Medium",
      targetSessionLength: 13,
      specialMechanics: ["Sticky Wilds", "Collection Mechanics"],
      primaryGoal: "High engagement",
      targetAudience: "Bonus seekers",
      sessionLength: "Medium",
      bonusImportance: "Core",
      earlyExcitement: "Moderate",
      reelType: "Video",
      paylineCount: 20,
      hasWild: true,
      wildType: "Sticky",
      stickyWildMode: "Until end of feature",
      hasScatter: true,
      scatterThreshold: 3,
      hasRetrigger: false,
      freeSpinCount: 10,
      freeGameReels: "Different reels",
      bonusBuyAvailable: false,
      anteBetAvailable: false,
      winPacing: "Bonus-dependent",
      requiresSimulation: false,
    },
    knownOutcomes: {
      marketPresence: "Medium",
      targetMarkets: ["EU", "Nordics"],
      estimatedSessionLengthMinutes: 13,
      sessionProfile: "Medium",
      primaryArchetype: "Bonus-Seeking Player",
      secondaryArchetype: "Casual Player",
      archetypeReason: "Western outlaw theme with bandit symbols that stick to reels when they land. The free spins feature is driven by collecting bandit symbols across the screen — the more bandits that stick, the higher the multiplier applied to the final collect. Mechanic appeals to patient bonus seekers who understand the building collect.",
      knownStrengths: [
        "Sticky bandit characters on reels creates engaging visual storytelling",
        "Collect mechanic with building sticky symbols is intuitive and satisfying",
        "High-quality Quickspin visuals and animations",
        "Western theme is well-differentiated from Egyptian/mythology saturation",
      ],
      knownWeaknesses: [
        "Medium market presence — Quickspin lacks Pragmatic/Play'n GO distribution scale",
        "3,375× max win is modest for a High volatility game",
        "Collect mechanic doesn't feel significantly distinct from Big Bass Bonanza",
      ],
      notes: "Released 2018. 20 paylines, 5×3. Bandit symbols (scatter) appear on all reels. In free spins, when bandits land they stick to their position AND add to a multiplier meter. All sticky bandits are collected at end of free spins, applying the accumulated multiplier to the total collected value. Spawned Sticky Bandits 3 Most Wanted (2020) and Trail of Dead (2021).",
    },
  },
];

// ── Validation runner helpers ─────────────────────────────────

/**
 * Returns entries grouped by archetype for accuracy analysis.
 */
export function getEntriesByArchetype(archetype: string): ValidationEntry[] {
  return VALIDATION_DATASET.filter(
    e => e.knownOutcomes.primaryArchetype === archetype ||
         e.knownOutcomes.secondaryArchetype === archetype
  );
}

/**
 * Returns entries grouped by volatility for model calibration.
 */
export function getEntriesByVolatility(volatility: string): ValidationEntry[] {
  return VALIDATION_DATASET.filter(e => e.gameConcept.volatility === volatility);
}

/**
 * Returns entries that require simulation (for flagging in validation runner).
 */
export function getSimulationRequiredEntries(): ValidationEntry[] {
  return VALIDATION_DATASET.filter(e => e.gameConcept.requiresSimulation === true);
}

/**
 * Summary statistics for quick dataset inspection.
 */
export function getDatasetSummary() {
  const byVolatility = {
    Low: VALIDATION_DATASET.filter(e => e.gameConcept.volatility === "Low").length,
    Medium: VALIDATION_DATASET.filter(e => e.gameConcept.volatility === "Medium").length,
    High: VALIDATION_DATASET.filter(e => e.gameConcept.volatility === "High").length,
    "Very High": VALIDATION_DATASET.filter(e => e.gameConcept.volatility === "Very High").length,
  };

  const byGameType = VALIDATION_DATASET.reduce<Record<string, number>>((acc, e) => {
    acc[e.gameConcept.gameType] = (acc[e.gameConcept.gameType] || 0) + 1;
    return acc;
  }, {});

  const avgSessionLength =
    VALIDATION_DATASET.reduce((s, e) => s + e.knownOutcomes.estimatedSessionLengthMinutes, 0) /
    VALIDATION_DATASET.length;

  return {
    totalGames: VALIDATION_DATASET.length,
    byVolatility,
    byGameType,
    avgSessionLengthMinutes: Math.round(avgSessionLength * 10) / 10,
    requiresSimulation: VALIDATION_DATASET.filter(e => e.gameConcept.requiresSimulation).length,
  };
}
